```{r}
# Importando Bibliotecas
library(readxl)
library(dplyr)
library(readr)
library(ggplot2)
library(ggthemes)
```

```{r}
# Trazendo o arquivo com os df coletados
# df <- read_excel("C:/Users/Raphael/Downloads/estatisticas_gerais.xlsx")
df <- read_excel("C:/Users/raphael.eugenio/Desktop/Raphael/WC26/estatisticas_gerais.xlsx")

library(stringr)
normalize_column_names <- function(df){
  # Remover acentuação
  colnames(df) <- iconv(colnames(df), from = "UTF-8", to = "ASCII//TRANSLIT")
  # Converter para minúsculas
  colnames(df) <- tolower(colnames(df))
  # Substituir espaços por underscores
  colnames(df) <- str_replace_all(colnames(df), " ", "_")
  # Remover caracteres especiais, mantendo apenas letras, números e underscores
  colnames(df) <- gsub("[^a-z0-9_]", "", colnames(df))
  # Substituir múltiplos underscores consecutivos por um único underscore
  colnames(df) <- gsub("+", "", colnames(df))
  # Remover underscores no início ou fim dos nomes de colunas
  colnames(df) <- gsub("^|$", "", colnames(df))
  return(df)
}
df = normalize_column_names(df)

View(df)
```

```{r}
# Arrumando os df para integer
df <- df %>%
  mutate(
    across(
      -c(time, continente, confederacao),
      parse_number
    )
  )
```


```{r}
df %>%
  select(partidas, gols_sofridos)

# Primeiro Grafico
ggplot(data = df, mapping = aes(x = partidas, y = gols_sofridos)) +
  geom_point() +
  geom_smooth(method = 'lm')

df$gols_marcados = df$gols_marcados / df$partidas
df['teste'] = df['gols_marcados'] / df['partidas']

df$gols_sofridos = df$gols_sofridos / df$partidas
df$assistencias = df$assistencias / df$partidas
df$gols_de_penalti = df$gols_de_penalti / df$partidas
df$gols_marcados = df$gols_marcados / df$partidas
df$gols_de_falta = df$gols_de_falta / df$partidas
df$gols_com_a_perna_esquerda = df$gols_com_a_perna_esquerda / df$partidas
df$gols_com_a_perna_direita = df$gols_com_a_perna_direita / df$partidas
df$gols_de_cabeca = df$gols_de_cabeca / df$partidas
df$finalizacoes_na_trave = df$finalizacoes_na_trave / df$partidas
```


```{r}
matriz_cor <- cor(df[, sapply(df, is.numeric)], use = "complete.obs")
matriz_cor %>% round(2)
```



```{r}

```

```{r}
# Visualizando as colunas e algumas linhas
glimpse(df)
```

```{r}
# Estruturas das colunas
summary(df)
```


```{r}
# Primeiro Grafico
ggplot(
  data = df,
  mapping = aes(x = gols_de_dentro_da_area, y = gols_marcados)
)+
  geom_point()+
  geom_smooth()
```

```{r}
ggplot(df, aes(x = total_de_finalizacoes_por_jogo, y = gols_sofridos)) +
  geom_point(aes(color = continente, shape = continente)) +
  geom_smooth(method = "lm") +
  labs(
    title = "Relação entre Finalizações e Gols Sofridos",
    subtitle = "Análise por continente",
    x = "Finalizações por jogo",
    y = "Gols sofridos",
    color = "continente",
    shape = "continente"
)+ scale_color_colorblind()
```

```{r}

```

```{r}
print('modelo simples')
modelo = lm(gols_sofridos ~ total_de_finalizacoes_por_jogo, data=df)
summary(modelo)

print('modelo multi 1')
modelo = lm(gols_sofridos ~ total_de_finalizacoes_por_jogo + assistencias + grandes_chances_perdidas_por_jogo + chutes_errados_por_jogo, data=df)
summary(modelo)

cor.test(
  df$total_de_finalizacoes_por_jogo,
  df$gols_sofridos,
  use = "complete.obs"
)
```


```{r}
str(df$gols_de_dentro_da_area)
str(df$gols_marcados)
```


```{r}

```


```{r}
ggplot(df, aes(x = posse_de_bola, y = gols_sofridos)) +
  geom_point(aes(color = continente, shape = continente)) +
  geom_smooth(method = "lm") +
  labs(
    title = "Relação entre Posse de bola e Gols sofridos",
    subtitle = "Análise por continente",
    x = "Posse de bola",
    y = "Gols sofridos",
    color = "continente",
    shape = "continente"
)
```
```{r}
print('modelo simples')
modelo = lm(posse_de_bola ~ gols_sofridos, data=df)
summary(modelo)

print('modelo multi 1')
modelo = lm(posse_de_bola ~ gols_sofridos + , data=df)
summary(modelo)

cor.test(
  df$total_de_finalizacoes_por_jogo,
  df$gols_sofridos,
  use = "complete.obs"
)
```

